import type { Message } from "./types";

export const MOCK_MESSAGES: Message[] = [
  {
    id: "1",
    source: "WhatsApp",
    sender: "Marc Dubois",
    initials: "MD",
    preview: "Le conseil d'administration demande un reporting avant vendredi.",
    date: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    read: false,
    priority: "urgent",
    aiPriority: "urgent",
    archived: false,
    pinned: false,
    thread: [
      {
        id: "1-1",
        content: "Bonjour, j'espère que tu vas bien.",
        date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Marc Dubois",
      },
      {
        id: "1-2",
        content: "Oui très bien, quoi de neuf ?",
        date: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
        fromMe: true,
      },
      {
        id: "1-3",
        content: "Le conseil d'administration demande un reporting avant vendredi.",
        date: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Marc Dubois",
      },
    ],
  },
  {
    id: "2",
    source: "LinkedIn",
    sender: "Sophie Chen",
    initials: "SC",
    preview: "Objet : Proposition de partenariat stratégique — Series B",
    date: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    read: false,
    priority: "urgent",
    aiPriority: "urgent",
    archived: false,
    pinned: true,
    thread: [
      {
        id: "2-1",
        content:
          "Bonjour, je suis directrice des investissements chez Accel Partners. Nous avons suivi votre croissance ces 18 derniers mois et serions très intéressés par une discussion autour d'une potentielle participation à votre prochain tour de table.",
        date: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Sophie Chen",
      },
    ],
  },
  {
    id: "3",
    source: "Email",
    sender: "Thomas Renard",
    initials: "TR",
    preview: "Rapport Q1 — quelques points à clarifier avant présentation",
    date: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    read: false,
    priority: "important",
    aiPriority: "important",
    archived: false,
    pinned: false,
    thread: [
      {
        id: "3-1",
        content:
          "Bonjour, j'ai terminé de compiler les chiffres du Q1. Il y a quelques points sur les marges opérationnelles en Europe du Sud que je souhaiterais clarifier avec toi avant de les présenter au comité de direction.",
        date: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Thomas Renard",
      },
      {
        id: "3-2",
        content: "Entendu, envoie-moi le draft ce soir.",
        date: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        fromMe: true,
      },
      {
        id: "3-3",
        content:
          "Voici le document en pièce jointe. Notamment pages 12-14 sur les coûts logistiques.",
        date: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Thomas Renard",
      },
    ],
  },
  {
    id: "4",
    source: "SMS",
    sender: "+33 6 12 34 56 78",
    initials: "CL",
    preview: "Rappelle-moi dès que possible, c'est urgent côté contrat.",
    date: new Date(Date.now() - 1.2 * 60 * 60 * 1000).toISOString(),
    read: false,
    priority: "urgent",
    aiPriority: "urgent",
    archived: false,
    pinned: false,
    thread: [
      {
        id: "4-1",
        content: "Rappelle-moi dès que possible, c'est urgent côté contrat.",
        date: new Date(Date.now() - 1.2 * 60 * 60 * 1000).toISOString(),
        fromMe: false,
      },
    ],
  },
  {
    id: "5",
    source: "LinkedIn",
    sender: "Antoine Moreau",
    initials: "AM",
    preview: "Candidature Head of Sales — disponible pour un call cette semaine",
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    read: false,
    priority: "normal",
    aiPriority: "normal",
    archived: false,
    pinned: false,
    thread: [
      {
        id: "5-1",
        content:
          "Bonjour, je suis actuellement Directeur Commercial chez Doctolib et je suis très intéressé par le poste de Head of Sales que vous recrutez. 8 ans d'expérience dans la SaaS B2B, je serais ravi d'échanger. Disponible cette semaine ?",
        date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Antoine Moreau",
      },
    ],
  },
  {
    id: "6",
    source: "Email",
    sender: "Investor Relations — Blackstone",
    initials: "BR",
    preview: "Demande de mise à jour : métriques d'acquisition client S1 2026",
    date: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    read: false,
    priority: "important",
    aiPriority: "important",
    archived: false,
    pinned: true,
    thread: [
      {
        id: "6-1",
        content:
          "Cher dirigeant, notre comité de suivi portefeuille souhaite obtenir les métriques d'acquisition client du premier semestre avant notre prochain board meeting le 15 avril. Pourriez-vous nous transmettre un deck mis à jour avant le 10 ?",
        date: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Investor Relations — Blackstone",
      },
    ],
  },
  {
    id: "7",
    source: "WhatsApp",
    sender: "Équipe Presse",
    initials: "EP",
    preview: "Le Monde souhaite une interview pour demain 14h — confirmer ?",
    date: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    read: true,
    priority: "important",
    aiPriority: "important",
    archived: false,
    pinned: false,
    thread: [
      {
        id: "7-1",
        content:
          "Le Monde souhaite une interview pour demain 14h pour leur dossier sur les scale-ups françaises. Ils veulent 30 min. Tu confirmes ?",
        date: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Équipe Presse",
      },
      {
        id: "7-2",
        content: "Je confirme, 30 min c'est parfait.",
        date: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
        fromMe: true,
      },
    ],
  },
  {
    id: "8",
    source: "Email",
    sender: "Pauline Garnier",
    initials: "PG",
    preview: "Compte rendu du board du 28 mars — actions à valider",
    date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    read: true,
    priority: "normal",
    aiPriority: "normal",
    archived: false,
    pinned: false,
    thread: [
      {
        id: "8-1",
        content:
          "Bonjour, veuillez trouver ci-joint le compte rendu officiel du board du 28 mars. Merci de valider les 3 actions qui vous sont assignées avant la fin de la semaine.",
        date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Pauline Garnier",
      },
    ],
  },
  {
    id: "9",
    source: "SMS",
    sender: "+33 7 98 76 54 32",
    initials: "JL",
    preview: "Déjeuner confirmé jeudi 12h30, table au nom de Laurent.",
    date: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    read: true,
    priority: "normal",
    aiPriority: "normal",
    archived: false,
    pinned: false,
    thread: [
      {
        id: "9-1",
        content: "Déjeuner confirmé jeudi 12h30, table au nom de Laurent.",
        date: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        fromMe: false,
      },
    ],
  },
  {
    id: "10",
    source: "LinkedIn",
    sender: "Laura Petit",
    initials: "LP",
    preview: "Félicitations pour votre levée de fonds — collaboration possible ?",
    date: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    read: true,
    priority: "normal",
    aiPriority: "normal",
    archived: false,
    pinned: false,
    thread: [
      {
        id: "10-1",
        content:
          "Bonjour, j'ai suivi avec attention l'annonce de votre levée de fonds. Chez Bain & Company nous accompagnons régulièrement des scale-ups en phase de croissance accélérée. Une conversation vous serait-elle utile ?",
        date: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        fromMe: false,
        senderName: "Laura Petit",
      },
    ],
  },
];
